import { ref } from 'vue'

const currentLang = ref('fr')

// Load language from localStorage if client-side
if (process.client) {
  const saved = localStorage.getItem('zekdrive_lang')
  if (saved && (saved === 'fr' || saved === 'en')) {
    currentLang.value = saved
  }
}

// Complete dictionary of translations in French and English
const dictionary: Record<string, Record<string, any>> = {
  fr: {
    nav: {
      home: 'Accueil',
      services: 'Services',
      becomeDriver: 'Devenir Chauffeur',
      pro: 'Pro',
      contact: 'Contact',
      download: "Télécharger l'App",
    },
    hero: {
      stars: '4.9/5 · +50 000 utilisateurs actifs',
      title_1: 'La mobilité urbaine',
      title_highlight: 'réinventée',
      title_2: 'en Afrique',
      sub: 'VTC, moto-taxi, livraison — rapide, fiable et abordable. ZekDrive vous connecte aux meilleurs chauffeurs en moins de 3 minutes.',
      users: 'Utilisateurs',
      drivers: 'Chauffeurs',
      rating: 'Note moyenne',
      discover: 'Découvrir',
    },
    stats: {
      users: 'Utilisateurs actifs',
      drivers: 'Chauffeurs vérifiés',
      trips: 'Trajets effectués',
      rating: 'Note moyenne',
    },
    services: {
      tag: 'Nos Services',
      title_1: 'Tout ce dont vous avez besoin,',
      title_highlight: 'en un seul clic',
      subtitle: "Que vous ayez besoin d'un VTC, d'une moto-taxi ou d'une livraison, ZekDrive vous couvre 24h/24, 7j/7.",
      vtc_title: 'VTC Premium',
      vtc_desc: "Confortez-vous à bord d'un véhicule climatisé avec des chauffeurs professionnels. Idéal pour vos déplacements d'affaires et sorties en toute élégance.",
      vtc_tag: 'Le plus populaire',
      moto_title: 'Moto-Taxi',
      moto_desc: "Traversez la ville en un éclair grâce à nos moto-taxis agiles. Évitez les embouteillages et arrivez à l'heure, à chaque fois.",
      moto_tag: 'Express',
      bike_title: 'Vélo',
      bike_desc: 'Déplacez-vous de manière écologique et économique avec notre service de vélo. Parfait pour les courtes distances en zone urbaine.',
      bike_tag: 'Éco-responsable',
      delivery_title: 'Livraison',
      delivery_desc: 'Envoyez vos colis en toute sécurité partout dans la ville. Suivi en temps réel, livraison garantie et assurance incluse.',
      delivery_tag: 'Fiable & Rapide',
    },
    howItWorks: {
      tag: 'Comment ça marche',
      title_1: 'Simple comme ',
      title_highlight: 'bonjour',
      subtitle: 'Trois étapes simples pour commencer à profiter de ZekDrive.',
      step1_title: "Téléchargez l'app",
      step1_desc: 'Disponible gratuitement sur App Store et Google Play. Créez votre compte en moins de 2 minutes.',
      step2_title: 'Réservez votre trajet',
      step2_desc: 'Entrez votre destination, choisissez votre type de véhicule et trouvez un chauffeur en moins de 3 min.',
      step3_title: 'Arrivez à destination',
      step3_desc: 'Suivez votre chauffeur en temps réel et arrivez à destination en toute sécurité et confort.',
    },
    features: {
      tag: 'Fonctionnalités',
      title_1: 'Conçu pour vous faire ',
      title_highlight: 'gagner du temps',
      subtitle: 'ZekDrive intègre tout ce dont vous avez besoin pour des déplacements sans stress.',
      feat1_title: 'Suivi en temps réel',
      feat1_desc: 'Suivez votre chauffeur sur la carte en direct avec une précision GPS optimale.',
      feat2_title: 'Paiements sécurisés',
      feat2_desc: 'Mobile money (Orange, MTN, Wave), carte bancaire ou espèces — vous choisissez.',
      feat3_title: 'Chauffeurs notés',
      feat3_desc: 'Chaque chauffeur est vérifié, noté et évalué par notre communauté.',
      feat4_title: 'Support 24/7',
      feat4_desc: 'Notre équipe est disponible à toute heure pour vous aider.',
      feat5_title: 'Multi-véhicules',
      feat5_desc: 'VTC, moto-taxi, vélo — choisissez selon votre budget et vos besoins.',
      feat6_title: 'Réservation rapide',
      feat6_desc: 'Trouvez un chauffeur disponible en moins de 2 minutes, garanti.',
    },
    download: {
      tag: 'Application Mobile',
      title_1: 'Téléchargez ',
      title_highlight: 'ZekDrive',
      desc: "Disponible gratuitement sur iOS et Android. Rejoignez des milliers d'utilisateurs qui font confiance à ZekDrive pour leurs déplacements quotidiens.",
      store_ios_lbl: 'Télécharger sur',
      store_android_lbl: 'Disponible sur',
      feat1: 'Disponible sur iOS & Android — 100% gratuit',
      feat2: 'Mises à jour régulières avec de nouvelles fonctionnalités',
      feat3: 'Interface disponible en français et en langues locales',
      feat4: 'Fonctionne même avec une connexion internet lente',
      scan: "Scannez pour télécharger l'application",
      reviews: '+12 400 avis',
    },
    testimonials: {
      tag: 'Témoignages',
      title_1: 'Ce que disent nos ',
      title_highlight: 'utilisateurs',
      subtitle: 'Des milliers de personnes font confiance à ZekDrive pour leurs déplacements quotidiens.',
      t1_text: "Incroyable ! J'arrive au bureau en 10 minutes maintenant. Les chauffeurs sont toujours ponctuels et les voitures sont impeccables. Je recommande vivement !",
      t2_text: "Les chauffeurs sont très professionnels et courtois. L'application est super simple à utiliser. C'est la meilleure plateforme de VTC que j'ai utilisée en Afrique.",
      t3_text: "La livraison est super rapide et fiable. J'utilise ZekDrive pour envoyer mes colis chaque semaine. Le suivi en temps réel est fantastique !",
      t4_text: "J'utilise le service moto-taxi tous les jours pour éviter les embouteillages. C'est rapide, abordable et les tarifs sont transparents. Bravo ZekDrive !",
      t5_text: "Excellent service ! Le paiement via Orange Money est super pratique. Je n'ai plus besoin d'avoir du liquide sur moi. L'application est parfaite.",
      t6_text: "ZekDrive Pro est parfait pour notre entreprise. On gère toutes nos courses professionnelles depuis un seul compte. Service client très réactif aussi !",
    },
    faq: {
      tag: 'FAQ',
      title_1: 'FAQ',
      title_highlight: 'fréquentes',
      subtitle: 'Tout ce que vous devez savoir sur ZekDrive.',
      q1_q: "Comment puis-je télécharger l'application ZekDrive ?",
      q1_a: "Vous pouvez télécharger ZekDrive gratuitement sur l'App Store (iOS) et sur Google Play (Android). Recherchez \"ZekDrive\" et installez l'application. L'inscription prend moins de 2 minutes.",
      q2_q: "Quels modes de paiement sont acceptés ?",
      q2_a: "ZekDrive accepte les paiements via Orange Money, MTN Mobile Money, Wave, les cartes bancaires Visa/Mastercard, ainsi que les espèces pour certains services. Vous pouvez sauvegarder votre méthode préférée dans l'app.",
      q3_q: "Dans quelles villes ZekDrive est-il disponible ?",
      q3_a: "ZekDrive est actuellement disponible à Dakar, Abidjan, Bamako, Kinshasa, Douala et en cours de déploiement dans d'autres grandes villes africaines. Activez les notifications pour être informé du lancement dans votre ville.",
      q4_q: "Comment sont sélectionnés et vérifiés les chauffeurs ?",
      q4_a: "Chaque chauffeur ZekDrive passe par un processus rigoureux de vérification : contrôle du permis de conduire, vérification de l'identité, inspection du véhicule et formation sur les standards de service. Ils sont ensuite régulièrement évalués par les utilisateurs.",
      q5_q: "Puis-je annuler une course ? Y a-t-il des frais ?",
      q5_a: "Vous pouvez annuler gratuitement dans les 2 premières minutes suivant votre réservation. Au-delà, des frais d'annulation minimes peuvent s'appliquer pour respecter le temps du chauffeur. Les détails sont affichés dans l'application avant confirmation.",
      q6_q: "Le service de livraison ZekDrive est-il assuré ?",
      q6_a: "Oui, tous les colis transportés via ZekDrive Livraison sont couverts par notre assurance jusqu'à une valeur déclarée. En cas de problème, notre support 24/7 est disponible pour traiter votre réclamation rapidement.",
      q7_q: "Comment puis-je devenir chauffeur partenaire ?",
      q7_a: "Rendez-vous sur la page \"Devenir Chauffeur\" de notre site ou dans la section Chauffeur de l'application. Remplissez le formulaire, fournissez vos documents (permis, pièce d'identité, carte grise) et passez l'entretien en ligne. Vous pouvez commencer en quelques jours.",
      q8_q: "ZekDrive propose-t-il des tarifs entreprise ?",
      q8_a: "Oui ! ZekDrive Pro offre des solutions dédiées aux entreprises : tableau de bord centralisé, facturation mensuelle, rapports de dépenses, et tarifs négociés pour les grands volumes. Visitez notre page Pro ou contactez-nous pour un devis.",
    },
    cta: {
      tag: 'Rejoignez-nous',
      title_1: 'Prêt à transformer vos',
      title_highlight: 'déplacements ?',
      sub: 'Téléchargez ZekDrive et bénéficiez de votre premier trajet avec 20% de réduction.',
      btn: "Télécharger l'App",
      btn_driver: 'Devenir chauffeur',
    },
    footer: {
      tagline: 'La mobilité urbaine réinventée en Afrique. VTC, moto-taxi, vélo et livraison — rapide, fiable, abordable.',
      download: 'Télécharger',
      services: 'Services',
      entreprise: 'Entreprise',
      legal: 'Légal',
      copyright: '© 2026 ZekDrive. Tous droits réservés. Conçu avec ❤️ pour l\'Afrique.',
      privacy: 'Confidentialité',
      terms: 'Conditions',
      cookies: 'Cookies',
      about: 'À propos',
      careers: 'Carrières',
      press: 'Presse',
      accessibility: 'Accessibilité',
    },
    driver: {
      meta_title: 'Devenir Chauffeur ZekDrive — Gagnez plus, conduisez librement',
      meta_desc: "Rejoignez les +500 chauffeurs ZekDrive. Horaires flexibles, paiement hebdomadaire, assurance incluse. Postulez dès aujourd'hui.",
      tag: 'Chauffeurs Partenaires',
      hero_title_1: 'Conduisez avec ZekDrive,',
      hero_title_highlight: 'Gagnez plus',
      hero_desc: "Rejoignez +500 chauffeurs partenaires et gagnez jusqu'à 350 000 FCFA par mois. Horaires flexibles, assurance incluse, paiement rapide.",
      btn_start: 'Commencer maintenant',
      btn_calc: 'Calculer mes gains',
      benefits_tag: 'Avantages',
      benefits_title_1: 'Pourquoi conduire avec ',
      benefits_title_highlight: 'ZekDrive ?',
      benefits_sub: 'Nous prenons soin de nos chauffeurs partenaires avec des avantages concrets.',
      b1_title: 'Horaires flexibles',
      b1_desc: 'Travaillez quand vous voulez, où vous voulez. Vous êtes votre propre patron.',
      b2_title: 'Paiement hebdomadaire',
      b2_desc: 'Recevez vos gains chaque semaine directement sur votre mobile money.',
      b3_title: 'Assurance incluse',
      b3_desc: 'Couverture assurance complète pendant vos courses. Conduisez en toute sérénité.',
      b4_title: 'Bonus de performance',
      b4_desc: 'Obtenez des bonus pour les courses supplémentaires et les bonnes notes.',
      b5_title: 'Formation gratuite',
      b5_desc: "Accès à notre programme de formation et d'accompagnement sans frais.",
      b6_title: 'Communauté solide',
      b6_desc: "Rejoignez une communauté de chauffeurs partenaires à travers toute l'Afrique.",
      req1_title: 'Inscrivez-vous en ligne',
      req1_desc: "Remplissez le formulaire d'inscription en moins de 5 minutes.",
      req2_title: 'Soumettez vos documents',
      req2_desc: "Permis de conduire, pièce d'identité et documents du véhicule.",
      req3_title: 'Entretien en ligne',
      req3_desc: 'Un court entretien vidéo pour vous présenter à notre équipe.',
      req4_title: 'Activation du compte',
      req4_desc: 'Votre compte est validé sous 48h. Commencez à gagner !',
      calc_tag: 'Calculateur',
      calc_title_1: 'Estimez vos ',
      calc_title_highlight: 'revenus',
      calc_sub: 'Ajustez vos paramètres pour estimer vos gains avec ZekDrive.',
      hours_label: 'Heures par jour',
      days_label: 'Jours par semaine',
      calc_week: 'Par semaine',
      calc_month: 'Par mois',
      calc_est: 'FCFA estimés',
      calc_note: '* Estimation basée sur le tarif horaire moyen de 2 800 FCFA. Les revenus réels peuvent varier selon la zone, la demande et le type de véhicule.',
      steps_tag: 'Comment postuler',
      steps_title_1: '4 étapes pour ',
      steps_title_highlight: 'commencer',
      form_tag: 'Candidature',
      form_title_1: 'Postulez ',
      form_title_highlight: 'maintenant',
      form_sub: 'Remplissez le formulaire et notre équipe vous contactera sous 24h.',
      first_name: 'Prénom *',
      last_name: 'Nom *',
      phone: 'Téléphone *',
      email: 'Email',
      city: 'Ville *',
      city_placeholder: 'Sélectionnez votre ville',
      vehicle_type: 'Type de véhicule *',
      vehicle_placeholder: 'Sélectionnez un type',
      vehicle_vtc: 'Voiture (VTC)',
      vehicle_moto: 'Moto-taxi',
      vehicle_bike: 'Vélo',
      experience: 'Expérience de conduite',
      exp_placeholder: "Années d'expérience",
      exp_1: "Moins d'1 an",
      exp_2: '1 à 3 ans',
      exp_3: '3 à 5 ans',
      exp_4: 'Plus de 5 ans',
      message: 'Message (optionnel)',
      message_placeholder: 'Parlez-nous de vous, de votre motivation...',
      btn_submit: 'Envoyer ma candidature',
      form_note: "En soumettant ce formulaire, vous acceptez nos conditions d'utilisation et notre politique de confidentialité.",
    },
    pro: {
      meta_title: 'ZekDrive Pro — Solutions de mobilité pour entreprises',
      meta_desc: 'ZekDrive Pro offre des solutions de mobilité clé en main pour les entreprises : courses professionnelles, livraisons, API et tarifs négociés.',
      tag: 'Pour les entreprises',
      hero_title_1: 'La mobilité pro',
      hero_title_highlight: 'sans compromis',
      hero_desc: 'Gerez tous vos déplacements professionnels avec une solution tout-en-un. Facturation centralisée, API, tableau de bord et support dédié.',
      btn_demo: 'Demander une démo',
      btn_prices: 'Voir les tarifs',
      trust_label: 'Ils nous font confiance',
      sol_tag: 'Solutions',
      sol_title_1: 'Tout ce dont votre ',
      sol_title_highlight: 'entreprise a besoin',
      sol1_title: 'Courses professionnelles',
      sol1_desc: 'Gérez tous vos déplacements professionnels depuis un tableau de bord centralisé. Suivi en temps réel, rapports de dépenses automatiques.',
      sol2_title: 'Livraison pour entreprises',
      sol2_desc: 'Expédiez vos documents, échantillons et colis grâce à notre flotte dédiée. Livraison express ou planifiée selon vos besoins.',
      sol3_title: 'Intégration API',
      sol3_desc: 'Intégrez ZekDrive directement dans vos outils métier via notre API REST. Documentée, sécurisée et supportée.',
      sol4_title: 'Reporting & Analytics',
      sol4_desc: 'Visualisez vos dépenses de mobilité, optimisez vos coûts avec des rapports détaillés et des exports personnalisés.',
      plan1_desc: 'Parfait pour les petites équipes et startups.',
      plan1_f1: 'Jusqu\'à 10 utilisateurs',
      plan1_f2: '50 courses/mois incluses',
      plan1_f3: 'Tableau de bord basique',
      plan1_f4: 'Facturation mensuelle',
      plan1_f5: 'Support email',
      plan2_desc: 'La solution complète pour les PME en croissance.',
      plan2_f1: 'Jusqu\'à 50 utilisateurs',
      plan2_f2: 'Courses illimitées',
      plan2_f3: 'Tableau de bord avancé',
      plan2_f4: 'Facturation & exports CSV',
      plan2_f5: 'API basique',
      plan2_f6: 'Support prioritaire 24/7',
      plan2_f7: 'Chauffeur dédié optionnel',
      plan3_desc: 'Solutions sur mesure pour les grandes entreprises.',
      plan3_f1: 'Utilisateurs illimités',
      plan3_f2: 'SLA garanti 99.9%',
      plan3_f3: 'API complète & webhooks',
      plan3_f4: 'Intégration ERP/SAP',
      plan3_f5: 'Manager dédié',
      plan3_f6: 'Formation équipe',
      plan3_f7: 'Contrat personnalisé',
      pricing_tag: 'Tarifs',
      pricing_title_1: 'Des plans adaptés à ',
      pricing_title_highlight: 'chaque besoin',
      pricing_sub: 'Commencez gratuitement, évoluez à votre rythme. Tous les plans incluent un essai de 30 jours.',
      plan_featured: 'Le plus choisi',
      plan_period: '/ mois',
      plan_cta_starter: 'Commencer gratuitement',
      plan_cta_business: 'Essai gratuit 30 jours',
      plan_cta_enterprise: "Contacter l'équipe",
      form_tag: 'Contact Pro',
      form_title_1: 'Parlons de votre ',
      form_title_highlight: 'projet',
      form_sub: 'Décrivez vos besoins et notre équipe vous contactera sous 24h.',
      company: 'Entreprise *',
      company_placeholder: 'Nom de votre entreprise',
      name: 'Votre nom *',
      name_placeholder: 'Prénom Nom',
      email_pro: 'Email professionnel *',
      email_pro_placeholder: 'vous@entreprise.com',
      employees: "Effectif de l'entreprise",
      emp_placeholder: 'Sélectionnez',
      plan_desired: 'Plan souhaité',
      plan_placeholder: 'Sélectionnez un plan',
      desc_needs: 'Décrivez vos besoins',
      desc_needs_placeholder: 'Parlez-nous de votre activité, vos besoins en mobilité, le volume mensuel estimé...',
      btn_submit: 'Envoyer ma demande',
    },
    contact: {
      meta_title: 'Contactez ZekDrive — Notre équipe est à votre écoute',
      validate_firstname: 'Le prénom est requis',
      validate_lastname: 'Le nom est requis',
      validate_email_req: "L'adresse e-mail est requise",
      validate_email_inv: "Format d'adresse e-mail invalide",
      validate_phone: 'Le numéro de téléphone est requis',
      validate_subject: 'Veuillez sélectionner un sujet',
      validate_message_empty: 'Le message ne peut pas être vide',
      validate_message_len: 'Le message doit contenir au moins 10 caractères',
      country_senegal: 'Sénégal',
      country_cotedivoire: "Côte d'Ivoire",
      country_mali: 'Mali',
      hours_dakar: 'Lun - Ven : 8h00 - 18h00',
      hours_abidjan: 'Lun - Ven : 8h00 - 18h00 / Sam : 9h00 - 13h00',
      hours_bamako: 'Lun - Ven : 8h00 - 17h30',
      meta_desc: "Une question, un partenariat ou besoin d'assistance ? Contactez le support ZekDrive à Dakar, Abidjan et Bamako. Nous vous répondons sous 24h.",
      tag: 'Contact & Support',
      hero_title_1: 'Une question ?',
      hero_title_highlight: 'Notre équipe est là',
      hero_sub: "Que vous soyez passager, chauffeur ou entreprise, nous répondons à vos besoins de mobilité partout en Afrique de l'Ouest.",
      card_phone: 'Téléphone',
      card_phone_sub: 'Assistance 7j/7, 24h/24',
      card_email: 'E-mail',
      card_email_sub: 'Réponse sous 24 heures ouvrées',
      card_hq: 'Siège social',
      card_hq_sub: 'Point E, Rue des Écrivains',
      presence_tag: 'Présence locale',
      presence_title_1: 'Nos ',
      presence_title_highlight: 'bureaux régionaux',
      presence_sub: "Découvrez nos hubs de support et centres d'accueil pour chauffeurs partenaires.",
      map_title: 'Carte interactive des hubs',
      office_hours: 'Horaires',
      office_phone: 'Téléphone',
      office_email: 'Email',
      form_tag: 'Formulaire de contact',
      form_title_1: 'Envoyez-nous un ',
      form_title_highlight: 'message',
      form_sub: 'Remplissez ce formulaire et nous reviendrons vers vous dans les plus brefs délais.',
      first_name: 'Prénom *',
      last_name: 'Nom *',
      email: 'Adresse e-mail *',
      phone: 'Téléphone *',
      type_label: 'Qui êtes-vous ?',
      type_passenger: 'Un passager',
      type_driver: 'Un chauffeur / futur partenaire',
      type_business: 'Une entreprise / partenaire pro',
      type_other: 'Autre demande',
      subject: 'Sujet *',
      subject_placeholder: 'Sélectionnez le sujet de votre message',
      subject_support: 'Support / Problème technique',
      subject_billing: 'Facturation / Paiement',
      subject_partner: 'Partenariat commercial',
      subject_career: 'Recrutement / Emploi',
      subject_other: 'Autre question',
      message: 'Message *',
      message_placeholder: 'Rédigez votre message ici (10 caractères minimum)...',
      btn_submit: 'Envoyer le message',
      btn_submitting: 'Envoi en cours...',
      success: 'Votre message a été envoyé avec succès ! Notre équipe vous répondra sous 24h.',
    },
    mockup: {
      vtc_title: 'Où allons-nous ?',
      delivery_title: 'Envoyer un colis',
      delivery_tab: 'Livraison',
      arrival: 'ARRIVÉE',
      distance_vtc: '2.4 km de distance',
      distance_del: '4.8 km de distance',
      fare: 'TARIF',
      fare_cfa: 'CFA estimé',
      confirm_vtc: 'Confirmer la course',
      confirm_del: "Confirmer l'envoi",
      delivery: 'LIVRAISON',
    }
  },
  en: {
    nav: {
      home: 'Home',
      services: 'Services',
      becomeDriver: 'Become a Driver',
      pro: 'Pro',
      contact: 'Contact',
      download: 'Download App',
    },
    hero: {
      stars: '4.9/5 · +50,000 active users',
      title_1: 'Urban mobility',
      title_highlight: 'reinvented',
      title_2: 'in Africa',
      sub: 'Cab, moto-taxi, delivery — fast, reliable and affordable. ZekDrive connects you to the best drivers in under 3 minutes.',
      users: 'Users',
      drivers: 'Drivers',
      rating: 'Average rating',
      discover: 'Discover',
    },
    stats: {
      users: 'Active users',
      drivers: 'Verified drivers',
      trips: 'Trips completed',
      rating: 'Average rating',
    },
    services: {
      tag: 'Our Services',
      title_1: 'Everything you need,',
      title_highlight: 'in a single click',
      subtitle: 'Whether you need a cab, a moto-taxi or a delivery, ZekDrive has you covered 24/7.',
      vtc_title: 'Premium Cab',
      vtc_desc: 'Relax in an air-conditioned vehicle with professional drivers. Ideal for business trips and elegant outings.',
      vtc_tag: 'Most popular',
      moto_title: 'Moto-Taxi',
      moto_desc: 'Zoom through the city in a flash with our agile moto-taxis. Avoid traffic jams and arrive on time, every time.',
      moto_tag: 'Express',
      bike_title: 'Bicycle',
      bike_desc: 'Get around ecologically and economically with our bicycle service. Perfect for short distances in urban areas.',
      bike_tag: 'Eco-friendly',
      delivery_title: 'Delivery',
      delivery_desc: 'Send your parcels safely anywhere in the city. Real-time tracking, guaranteed delivery, and insurance included.',
      delivery_tag: 'Fast & Reliable',
    },
    howItWorks: {
      tag: 'How it works',
      title_1: 'Easy as ',
      title_highlight: 'one, two, three',
      subtitle: 'Three simple steps to start enjoying ZekDrive.',
      step1_title: 'Download the app',
      step1_desc: 'Available for free on App Store and Google Play. Create your account in under 2 minutes.',
      step2_title: 'Book your ride',
      step2_desc: 'Enter your destination, choose your vehicle type, and find a driver in less than 3 minutes.',
      step3_title: 'Arrive at destination',
      step3_desc: 'Track your driver in real-time and arrive at your destination in complete safety and comfort.',
    },
    features: {
      tag: 'Features',
      title_1: 'Designed to save ',
      title_highlight: 'you time',
      subtitle: 'ZekDrive integrates everything you need for stress-free travel.',
      feat1_title: 'Real-time tracking',
      feat1_desc: 'Follow your driver on the live map with optimal GPS accuracy.',
      feat2_title: 'Secure payments',
      feat2_desc: 'Mobile money (Orange, MTN, Wave), credit card, or cash — you choose.',
      feat3_title: 'Rated drivers',
      feat3_desc: 'Every driver is verified, rated, and evaluated by our community.',
      feat4_title: '24/7 Support',
      feat4_desc: 'Our team is available at any time of day or night to help you.',
      feat5_title: 'Multi-vehicle options',
      feat5_desc: 'Cab, moto-taxi, bicycle — choose according to your budget and needs.',
      feat6_title: 'Fast booking',
      feat6_desc: 'Find an available driver in less than 2 minutes, guaranteed.',
    },
    download: {
      tag: 'Mobile Application',
      title_1: 'Download ',
      title_highlight: 'ZekDrive',
      desc: 'Available for free on iOS and Android. Join thousands of users who trust ZekDrive for their daily commute.',
      store_ios_lbl: 'Download on the',
      store_android_lbl: 'Get it on',
      feat1: 'Available on iOS & Android — 100% free',
      feat2: 'Regular updates with brand new features',
      feat3: 'Interface available in French and local languages',
      feat4: 'Works even with a slow internet connection',
      scan: 'Scan to download the application',
      reviews: '+12,400 reviews',
    },
    testimonials: {
      tag: 'Testimonials',
      title_1: 'What our ',
      title_highlight: 'users say',
      subtitle: 'Thousands of people trust ZekDrive for their daily travel.',
      t1_text: "Amazing! I get to the office in 10 minutes now. Drivers are always on time and cars are spotless. Highly recommend!",
      t2_text: "Drivers are extremely professional and courteous. The app is super easy to use. Best ride-hailing platform I have used in Africa.",
      t3_text: "Delivery is super fast and reliable. I use ZekDrive to send packages every week. Real-time tracking is fantastic!",
      t4_text: "I use the moto-taxi service every day to avoid traffic jams. It is fast, affordable and pricing is transparent. Well done ZekDrive!",
      t5_text: "Excellent service! Payment via Orange Money is very convenient. No cash needed anymore. Perfect app.",
      t6_text: "ZekDrive Pro is perfect for our business. We manage all our professional rides from a single dashboard. Great support too!",
    },
    faq: {
      tag: 'FAQ',
      title_1: 'Frequently Asked ',
      title_highlight: 'Questions',
      subtitle: 'Everything you need to know about ZekDrive.',
      q1_q: "How can I download the ZekDrive application?",
      q1_a: "You can download ZekDrive for free on the App Store (iOS) and Google Play (Android). Search for \"ZekDrive\" and install the app. Registration takes less than 2 minutes.",
      q2_q: "What payment methods are accepted?",
      q2_a: "ZekDrive accepts payments via Orange Money, MTN Mobile Money, Wave, Visa/Mastercard credit cards, as well as cash for certain services. You can save your preferred method in the app.",
      q3_q: "In which cities is ZekDrive available?",
      q3_a: "ZekDrive is currently available in Dakar, Abidjan, Bamako, Kinshasa, Douala and is being rolled out in other major African cities. Turn on notifications to be informed of the launch in your city.",
      q4_q: "How are drivers selected and verified?",
      q4_a: "Every ZekDrive driver goes through a rigorous verification process: driver's license check, background/identity check, vehicle inspection, and training on service standards. They are then regularly rated by users.",
      q5_q: "Can I cancel a ride? Are there fees?",
      q5_a: "You can cancel for free within the first 2 minutes of your reservation. Beyond that, a small cancellation fee may apply to respect the driver's time. Details are shown in the app before confirmation.",
      q6_q: "Is the ZekDrive delivery service insured?",
      q6_a: "Yes, all packages transported via ZekDrive Delivery are covered by our insurance up to a declared value. In case of any issue, our 24/7 support is available to process your claim quickly.",
      q7_q: "How can I become a partner driver?",
      q7_a: "Go to the \"Become a Driver\" page on our site or in the Driver section of the app. Fill out the form, submit your documents (license, ID, vehicle registration), and pass the online interview. You can start in a few days.",
      q8_q: "Does ZekDrive offer business rates?",
      q8_a: "Yes! ZekDrive Pro offers dedicated corporate solutions: centralized dashboard, monthly billing, expense reports, and negotiated rates for high volumes. Visit our Pro page or contact us for a quote.",
    },
    cta: {
      tag: 'Join us',
      title_1: 'Ready to transform your',
      title_highlight: 'commute?',
      sub: 'Download ZekDrive and get 20% off your first ride.',
      btn: 'Download the App',
      btn_driver: 'Become a driver',
    },
    footer: {
      tagline: 'Urban mobility reinvented in Africa. Premium cabs, moto-taxis, bicycles and delivery — fast, reliable, affordable.',
      download: 'Download',
      services: 'Services',
      entreprise: 'Company',
      legal: 'Legal',
      copyright: '© 2026 ZekDrive. All rights reserved. Designed with ❤️ for Africa.',
      privacy: 'Privacy Policy',
      terms: 'Terms of Use',
      cookies: 'Cookies',
      about: 'About Us',
      careers: 'Careers',
      press: 'Press',
      accessibility: 'Accessibility',
    },
    driver: {
      meta_title: 'Become a ZekDrive Driver — Earn more, drive freely',
      meta_desc: 'Join +500 ZekDrive drivers. Flexible hours, weekly payment, insurance included. Apply today.',
      tag: 'Partner Drivers',
      hero_title_1: 'Drive with ZekDrive,',
      hero_title_highlight: 'Earn more',
      hero_desc: 'Join +500 partner drivers and earn up to 350,000 FCFA per month. Flexible hours, insurance included, fast payouts.',
      btn_start: 'Get started now',
      btn_calc: 'Calculate my earnings',
      benefits_tag: 'Benefits',
      benefits_title_1: 'Why drive with ',
      benefits_title_highlight: 'ZekDrive?',
      benefits_sub: 'We take care of our partner drivers with concrete benefits.',
      b1_title: 'Flexible hours',
      b1_desc: 'Work when you want, where you want. You are your own boss.',
      b2_title: 'Weekly payout',
      b2_desc: 'Receive your earnings every week directly on your mobile money.',
      b3_title: 'Insurance included',
      b3_desc: 'Comprehensive insurance coverage during your rides. Drive with peace of mind.',
      b4_title: 'Performance bonus',
      b4_desc: 'Get bonuses for extra trips and good ratings.',
      b5_title: 'Free training',
      b5_desc: 'Access to our training and support program at no cost.',
      b6_title: 'Solid community',
      b6_desc: 'Join a community of partner drivers across Africa.',
      req1_title: 'Register online',
      req1_desc: 'Fill out the registration form in less than 5 minutes.',
      req2_title: 'Submit your documents',
      req2_desc: "Driver's license, ID card and vehicle documents.",
      req3_title: 'Online interview',
      req3_desc: 'A short video interview to introduce yourself to our team.',
      req4_title: 'Account activation',
      req4_desc: 'Your account is validated within 48 hours. Start earning!',
      calc_tag: 'Calculator',
      calc_title_1: 'Estimate your ',
      calc_title_highlight: 'earnings',
      calc_sub: 'Adjust your settings to estimate your earnings with ZekDrive.',
      hours_label: 'Hours per day',
      days_label: 'Days per week',
      calc_week: 'Per week',
      calc_month: 'Per month',
      calc_est: 'estimated FCFA',
      calc_note: '* Estimate based on average hourly rate of 2,800 FCFA. Real earnings may vary depending on zone, demand and vehicle type.',
      steps_tag: 'How to apply',
      steps_title_1: '4 steps to ',
      steps_title_highlight: 'get started',
      form_tag: 'Application',
      form_title_1: 'Apply ',
      form_title_highlight: 'now',
      form_sub: 'Fill out the form and our team will contact you within 24 hours.',
      first_name: 'First Name *',
      last_name: 'Last Name *',
      phone: 'Phone Number *',
      email: 'Email Address',
      city: 'City *',
      city_placeholder: 'Select your city',
      vehicle_type: 'Vehicle Type *',
      vehicle_placeholder: 'Select a type',
      vehicle_vtc: 'Car (VTC)',
      vehicle_moto: 'Moto-taxi',
      vehicle_bike: 'Bicycle',
      experience: 'Driving Experience',
      exp_placeholder: 'Years of experience',
      exp_1: 'Less than 1 year',
      exp_2: '1 to 3 years',
      exp_3: '3 to 5 years',
      exp_4: 'More than 5 years',
      message: 'Message (optional)',
      message_placeholder: 'Tell us about yourself, your motivation...',
      btn_submit: 'Submit application',
      form_note: 'By submitting this form, you agree to our terms of use and privacy policy.',
    },
    pro: {
      meta_title: 'ZekDrive Pro — Mobility solutions for businesses',
      meta_desc: 'ZekDrive Pro provides turnkey mobility solutions for businesses: professional rides, deliveries, API, and negotiated rates.',
      tag: 'For Businesses',
      hero_title_1: 'Professional mobility',
      hero_title_highlight: 'without compromise',
      hero_desc: 'Manage all your corporate travel with an all-in-one solution. Centralized billing, API, dashboard and dedicated support.',
      btn_demo: 'Request a demo',
      btn_prices: 'See pricing plans',
      trust_label: 'They trust us',
      sol_tag: 'Solutions',
      sol_title_1: 'Everything your ',
      sol_title_highlight: 'business needs',
      sol1_title: 'Corporate rides',
      sol1_desc: 'Manage all your business travels from a centralized dashboard. Real-time tracking, automatic expense reports.',
      sol2_title: 'Corporate delivery',
      sol2_desc: 'Ship your documents, samples and parcels using our dedicated fleet. Express or planned delivery as needed.',
      sol3_title: 'API Integration',
      sol3_desc: 'Integrate ZekDrive directly into your business tools via our REST API. Fully documented, secure and supported.',
      sol4_title: 'Reporting & Analytics',
      sol4_desc: 'Visualize your mobility expenses, optimize your costs with detailed reports and custom exports.',
      plan1_desc: 'Perfect for small teams and startups.',
      plan1_f1: 'Up to 10 users',
      plan1_f2: '50 rides/month included',
      plan1_f3: 'Basic dashboard',
      plan1_f4: 'Monthly billing',
      plan1_f5: 'Email support',
      plan2_desc: 'The complete solution for growing SMEs.',
      plan2_f1: 'Up to 50 users',
      plan2_f2: 'Unlimited rides',
      plan2_f3: 'Advanced dashboard',
      plan2_f4: 'Billing & CSV exports',
      plan2_f5: 'Basic API',
      plan2_f6: '24/7 Priority support',
      plan2_f7: 'Optional dedicated driver',
      plan3_desc: 'Tailor-made solutions for large enterprises.',
      plan3_f1: 'Unlimited users',
      plan3_f2: '99.9% Guaranteed SLA',
      plan3_f3: 'Full API & webhooks',
      plan3_f4: 'ERP/SAP Integration',
      plan3_f5: 'Dedicated account manager',
      plan3_f6: 'Team onboarding & training',
      plan3_f7: 'Custom contract options',
      pricing_tag: 'Pricing',
      pricing_title_1: 'Plans tailored to ',
      pricing_title_highlight: 'every need',
      pricing_sub: 'Start for free, scale at your own pace. All plans include a 30-day trial.',
      plan_featured: 'Most popular',
      plan_period: '/ month',
      plan_cta_starter: 'Get started for free',
      plan_cta_business: '30-day free trial',
      plan_cta_enterprise: 'Contact our team',
      form_tag: 'Contact Pro',
      form_title_1: 'Let’s discuss your ',
      form_title_highlight: 'project',
      form_sub: 'Describe your needs and our team will contact you within 24 hours.',
      company: 'Company *',
      company_placeholder: 'Name of your company',
      name: 'Your Name *',
      name_placeholder: 'First and Last Name',
      email_pro: 'Work Email *',
      email_pro_placeholder: 'you@company.com',
      employees: 'Company Size',
      emp_placeholder: 'Select size',
      plan_desired: 'Desired Plan',
      plan_placeholder: 'Select a plan',
      desc_needs: 'Describe your needs',
      desc_needs_placeholder: 'Tell us about your activity, mobility needs, estimated monthly volume...',
      btn_submit: 'Send Request',
    },
    contact: {
      meta_title: 'Contact ZekDrive — Our team is listening',
      validate_firstname: 'First name is required',
      validate_lastname: 'Last name is required',
      validate_email_req: 'Email address is required',
      validate_email_inv: 'Invalid email address format',
      validate_phone: 'Phone number is required',
      validate_subject: 'Please select a subject',
      validate_message_empty: 'Message cannot be empty',
      validate_message_len: 'Message must contain at least 10 characters',
      country_senegal: 'Senegal',
      country_cotedivoire: 'Ivory Coast',
      country_mali: 'Mali',
      hours_dakar: 'Mon - Fri: 8:00 AM - 6:00 PM',
      hours_abidjan: 'Mon - Fri: 8:00 AM - 6:00 PM / Sat: 9:00 AM - 1:00 PM',
      hours_bamako: 'Mon - Fri: 8:00 AM - 5:30 PM',
      meta_desc: 'Any questions, partnerships or support needs? Contact ZekDrive support in Dakar, Abidjan and Bamako. We reply within 24h.',
      tag: 'Contact & Support',
      hero_title_1: 'Any questions?',
      hero_title_highlight: 'Our team is here',
      hero_sub: 'Whether you are a rider, driver or enterprise, we address your mobility needs anywhere in West Africa.',
      card_phone: 'Phone',
      card_phone_sub: '7/7, 24/24 Assistance',
      card_email: 'Email',
      card_email_sub: 'Reply within 24 business hours',
      card_hq: 'Headquarters',
      card_hq_sub: 'Point E, Writers Street',
      presence_tag: 'Local Presence',
      presence_title_1: 'Our ',
      presence_title_highlight: 'regional offices',
      presence_sub: 'Discover our support hubs and onboarding centers for partner drivers.',
      map_title: 'Interactive hub map',
      office_hours: 'Hours',
      office_phone: 'Phone',
      office_email: 'Email',
      form_tag: 'Contact Form',
      form_title_1: 'Send us a ',
      form_title_highlight: 'message',
      form_sub: 'Fill out this form and we will get back to you as soon as possible.',
      first_name: 'First Name *',
      last_name: 'Last Name *',
      email: 'Email Address *',
      phone: 'Phone Number *',
      type_label: 'Who are you?',
      type_passenger: 'A rider / passenger',
      type_driver: 'A driver / future partner',
      type_business: 'A business / corporate partner',
      type_other: 'Other inquiry',
      subject: 'Subject *',
      subject_placeholder: 'Select the subject of your message',
      subject_support: 'Support / Technical Issue',
      subject_billing: 'Billing / Payment',
      subject_partner: 'Business Partnership',
      subject_career: 'Careers / Jobs',
      subject_other: 'Other question',
      message: 'Message *',
      message_placeholder: 'Write your message here (10 characters minimum)...',
      btn_submit: 'Send Message',
      btn_submitting: 'Sending...',
      success: 'Your message has been sent successfully! Our team will get back to you within 24 hours.',
    },
    mockup: {
      vtc_title: 'Where to?',
      delivery_title: 'Send a package',
      delivery_tab: 'Delivery',
      arrival: 'ARRIVAL',
      distance_vtc: '2.4 km away',
      distance_del: '4.8 km away',
      fare: 'FARE',
      fare_cfa: 'estimated CFA',
      confirm_vtc: 'Confirm Ride',
      confirm_del: 'Confirm Delivery',
      delivery: 'DELIVERY',
    }
  }
}

function getNestedValue(obj: any, path: string): string {
  const keys = path.split('.')
  let current = obj
  for (const key of keys) {
    if (current && typeof current === 'object' && key in current) {
      current = current[key]
    } else {
      return path
    }
  }
  return typeof current === 'string' ? current : path
}

export function useLanguage() {
  const t = (path: string): string => {
    const lang = currentLang.value
    const langDict = dictionary[lang] || dictionary.fr
    return getNestedValue(langDict, path)
  }

  const setLanguage = (lang: 'fr' | 'en') => {
    currentLang.value = lang
    if (process.client) {
      localStorage.setItem('zekdrive_lang', lang)
    }
  }

  const toggleLanguage = () => {
    setLanguage(currentLang.value === 'fr' ? 'en' : 'fr')
  }

  return {
    currentLang,
    t,
    setLanguage,
    toggleLanguage,
  }
}
