DROP TABLE IF EXISTS deliveries;
DROP TABLE IF EXISTS trips;
DROP TABLE IF EXISTS zones;
DROP TABLE IF EXISTS vehicles;
DROP TABLE IF EXISTS drivers;
DROP TABLE IF EXISTS users;

DROP EXTENSION IF EXISTS postgis;
