package handler

const (
	AboutUsName      = "À propos de ZekDrive"
	AboutUsShort     = "ZekDrive - Votre partenaire de mobilité et de livraison de confiance."
	AboutUsLong      = `<p>ZekDrive est la plateforme technologique de référence conçue pour simplifier la mobilité urbaine et la livraison rapide de marchandises en Afrique et à l'international. Notre mission est de connecter les passagers avec des chauffeurs professionnels et fiables, tout en offrant aux commerces de proximité un canal performant pour livrer leurs produits en un temps record.</p><p>En combinant innovation technologique, sécurité renforcée et tarifs équitables, ZekDrive se positionne comme l'outil indispensable du quotidien pour les particuliers, les travailleurs indépendants et les entreprises locales. Nous croyons fermement en une économie collaborative inclusive et durable.</p>`

	PrivacyPolicyName  = "Politique de Confidentialité"
	PrivacyPolicyShort = "Politique de protection des données personnelles de la plateforme ZekDrive."
	PrivacyPolicyLong  = `<h3>1. Collecte des Données</h3><p>ZekDrive collecte les informations nécessaires au bon fonctionnement de ses services, notamment : votre identité (nom, e-mail, téléphone), vos données de géolocalisation en temps réel (pour la mise en relation et le suivi des trajets), les informations relatives à votre véhicule (pour les chauffeurs) et vos transactions financières.</p><h3>2. Utilisation des Données</h3><p>Vos données sont exclusivement utilisées pour : le calcul des itinéraires et la tarification, la mise en relation passager-chauffeur, la facturation des courses, l'envoi de codes d'authentification OTP par WhatsApp/SMS, et l'amélioration de la sécurité sur notre réseau (prévention des fraudes et audits système).</p><h3>3. Partage des Données</h3><p>Vos coordonnées de localisation et de profil sont partagées avec le chauffeur désigné uniquement durant la course. Aucune donnée personnelle n'est vendue à des tiers ou partagée sans consentement explicite.</p><h3>4. Vos Droits</h3><p>Conformément aux réglementations sur la protection des données personnelles (RGPD et législations locales), vous disposez d'un droit d'accès, de rectification et de suppression complète de vos données depuis votre profil ou en contactant notre support.</p>`

	TermsAndConditionsName  = "Conditions Générales d'Utilisation"
	TermsAndConditionsShort = "Conditions contractuelles d'utilisation de la plateforme ZekDrive."
	TermsAndConditionsLong  = `<h3>1. Acceptation des Conditions</h3><p>En créant un compte sur ZekDrive, vous acceptez sans réserve les présentes Conditions Générales d'Utilisation (CGU). L'accès à la plateforme est réservé aux personnes majeures et juridiquement capables.</p><h3>2. Services de Transport et Livraison</h3><p>ZekDrive fournit une plateforme technologique mettant en relation des clients avec des chauffeurs indépendants. ZekDrive n'est pas un transporteur public et ne fournit pas de services de transport en propre. Les chauffeurs sont seuls responsables de la bonne exécution des trajets et de la conformité de leur véhicule.</p><h3>3. Tarifs et Paiement</h3><p>Le prix estimé d'une course est calculé en fonction de la distance, de la durée estimée et de la configuration du pays d'origine. Les paiements s'effectuent en espèces (Cash) ou via les portefeuilles mobiles agréés (Wave, Orange Money) intégrés dans l'application. La commission de la plateforme est prélevée automatiquement.</p><h3>4. Règles de Conduite et Sécurité</h3><p>Tout utilisateur s'engage à faire preuve de courtoisie et de respect. ZekDrive se réserve le droit de suspendre ou de supprimer immédiatement tout compte présentant des comportements inappropriés, frauduleux ou non conformes aux lois en vigueur.</p>`

	LegalNoticeName  = "Mentions Légales"
	LegalNoticeShort = "Informations légales et hébergement de la plateforme ZekDrive."
	LegalNoticeLong  = `<p><strong>Éditeur de la plateforme :</strong> ZekDrive Inc. SAS au capital de 10 000 000 FCFA, immatriculée sous le numéro SN-DKR-2026-B-1234, dont le siège social est situé à Dakar, Sénégal.</p><p><strong>Directeur de la publication :</strong> Maxime Etundi - contact@rodriguendeffo.com</p><p><strong>Hébergement de la plateforme :</strong> IONOS Cloud - 7 Place de la Gare, 57000 Metz, France.</p><p><strong>Support et réclamations :</strong> support@zekdrive.com / +221 33 800 0000</p>`
)
